### ISSUE TITLE
Can we merge node-dot-arcanist?

### ISSUE THREAD

**Issue by sectioneight** [uber/arcanist#5]
AFAICT https://github.com/uber/node-dot-arcanist exists solely to work around the fact that we didn't have a fork. Can we deprecate that project and remove the functionality from our jenkins plugin?

**Comment by sectioneight** [comment]
@malandrew

**Comment by malandrew** [comment]
Yes, it is deprecated. Should we delete the repo and unpublish it from npm?

**Comment by Raynos** [comment]
Don't you dare unpublish anything from npm.

**Comment by Raynos** [comment]
Also don't delete the repository; people are still using it.

**Comment by malandrew** [comment]
Affirmative on not unpublishing. 

Regarding the repository, that's okay too. However, any new differential to a repository using .arcanist plugin folder will trigger a herald rule blocking that revision until they fix that.

**Comment by Raynos** [comment]
@malandrew that's fine; Having a .arcanist folder locally is bad. Having one in node_modules is fine.

**Comment by sectioneight** [comment]
Bump @malandrew -- can I remove the "npm install uber-dot-arcanist" logic from our jenkins plugin?

**Comment by sectioneight** [comment]
Removing from Jenkins plugin
